%dev.app.mode=DEVELOPMENT MODE
%prod.app.mode=PRODUCTION MODE
app.version=1.0.0
# HTTP configuration
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,PUT,DELETE
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.exposed-headers=*
## Allow credentials (cookies, authorization headers, etc.) if needed
quarkus.http.cors.access-control-allow-credentials=true
# Keycloak configuration
quarkus.oidc.auth-server-url=https://test-gitlab-keycloak.app.cloud.cbh.kth.se/realms/gitlab-realm
quarkus.oidc.client-id=ducklake
quarkus.oidc.application-type=service
## Allow longer wait for keycloak
quarkus.oidc.use-blocking-dns-lookup=true
quarkus.vertx.warning-exception-time=5S
quarkus.vertx.max-event-loop-execute-time=5S
quarkus.smallrye-jwt.enabled=true
## Enabling OIDC authentication for secured endpoints
quarkus.http.auth.permission.authenticated.paths=/api/*
quarkus.http.auth.permission.authenticated.policy=authenticated
# OpenAPI configuration
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.always-include=true
# PostgreSQL (Backend DB)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/backend_db
## Migration configuration
quarkus.flyway.migrate-at-start=true
## Prevent Hibernate/Panache from generating schema
quarkus.hibernate-orm.schema-management.strategy=validate
# Ducklake Catalog (Custom Config)
app.ducklake.catalog.host=localhost
app.ducklake.catalog.port=5432
app.ducklake.catalog.username=postgres
app.ducklake.catalog.password=postgres
app.ducklake.catalog.alias=lake

app.ducklake.garage.region=garage
app.ducklake.garage.endpoint=ducklake-garage:3900
app.ducklake.garage.url-style=path
app.ducklake.garage.use-ssl=false
# Garage Configuration
quarkus.rest-client.garage-admin.url=http://localhost:3903
app.garage.admin.token=<token_string>
app.garage.s3.endpoint=http://localhost:3903
app.garage.s3.region=garage
### Garage S3 Client config
quarkus.s3.endpoint-override=http://127.0.0.1:3900
quarkus.s3.aws.region=garage
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=<GARAGE_ACCESS_KEY>
quarkus.s3.aws.credentials.static-provider.secret-access-key=<GARAGE_SECRET_KEY>
quarkus.s3.path-style-access=true

